baseships/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from main import urls as main_urls


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(main_urls))
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import url

from main import views


urlpatterns = [
    url(
        r'^$',
        views.HomepageView.as_view(),
        name='homepage',
    ),

    url(
        r'^new$',
        views.NewGameView.as_view(),
        name='new_game',
    ),

    url(
        r'^game/(?P<pk>[\d]+)$',
        views.GameDetailView.as_view(),
        name='game_detail',
    ),

    url(
        r'^move$',
        views.move,
        name='move',
    ),
]

main/models.py
import json

from django.core.urlresolvers import reverse
from django.db import models


BOARD_SIZE = 10
FIELDS_LENGTH = len(json.dumps([[0] * BOARD_SIZE] * BOARD_SIZE))
SHIPS = [5, 4, 3, 2, 2, 1, 1]


class State(object):
    EMPTY = 0
    FILLED = 1
    MISSED = 2
    HIT = 3
    SUNK = 4


class Game(models.Model):
    player_board = models.CharField(max_length=FIELDS_LENGTH, blank=False, null=False)
    ai_board = models.CharField(max_length=FIELDS_LENGTH, blank=False, null=False)

    player_ships = models.CharField(max_length=FIELDS_LENGTH*2, blank=False, null=False)
    ai_ships = models.CharField(max_length=FIELDS_LENGTH*2, blank=False, null=False)

    player = models.ForeignKey('auth.User')

    def get_absolute_url(self):
        return reverse('game_detail', kwargs={'pk': self.pk})

    def update_player_board(self, x, y, state):
        self._update_board('player', x, y, state)

    def update_ai_board(self, x, y, state):
        self._update_board('ai', x, y, state)

    def hit_player_ship(self, x, y):
        return self._hit_ship('player', x, y)

    def hit_ai_ship(self, x, y):
        return self._hit_ship('ai', x, y)

    def game_over(self):
        filled = str(State.FILLED)

        if filled not in ''.join(json.loads(self.player_board)):
            return 'D'
        elif filled not in ''.join(json.loads(self.ai_board)):
            return 'V'

        return False

    def _update_board(self, owner, x, y, state):
        field_name = '{}_board'.format(owner)
        board = json.loads(getattr(self, field_name))
        row = list(board[x])

        row[y] = str(state)
        board[x] = ''.join(row)

        setattr(self, field_name, json.dumps(board))
        self.save()

    def _hit_ship(self, owner, x, y):
        ships_field_name = '{}_ships'.format(owner)
        board_field_name = '{}_board'.format(owner)
        ships = json.loads(getattr(self, ships_field_name))
        board = json.loads(getattr(self, board_field_name))
        point = [x, y]
        sunk = []
        state = State.HIT

        for ship in ships:
            if point in ship:
                if all(int(board[i][j]) == State.HIT for (i, j) in ship if [i, j] != point):
                    state = State.SUNK
                    sunk = ship

                    for i, j in ship:
                        if [i, j] != point:
                            self._update_board(owner, i, j, state)
                break

        setattr(self, ships_field_name, json.dumps(ships))
        self.save()
        self._update_board(owner, x, y, state)

        return state, sunk

main/forms.py
import json
import re

from django import forms

from main.models import BOARD_SIZE, SHIPS


class NewGameForm(forms.Form):
    fields = forms.CharField(max_length=BOARD_SIZE**2, min_length=BOARD_SIZE**2, widget=forms.HiddenInput())
    ships = forms.CharField(max_length=BOARD_SIZE**2*2, widget=forms.HiddenInput())

    def clean_fields(self):
        fields = self.cleaned_data['fields']

        if not re.match('^[01]*$', fields):
            raise forms.ValidationError('Incorrect data provided!')

        if fields.count('1') < 2:
            raise forms.ValidationError('Too few ships!')

        return [fields[i:i+BOARD_SIZE] for i in range(0, BOARD_SIZE**2, BOARD_SIZE)]  # convert str to list

    def clean_ships(self):
        ships = json.loads(self.cleaned_data['ships'])

        if not isinstance(ships, list) or not isinstance(ships[0], list):
            raise forms.ValidationError('Incorrect data provided!')

        points = set(str(part) for ship in ships for part in ship)
        if len(points) != sum(SHIPS):
            raise forms.ValidationError('At least one of your ships is not completed!')

        for ship in ships:
            x = sorted(point[0] for point in ship)
            y = sorted(point[1] for point in ship)

            x_set = set(x)
            y_set = set(y)

            if len(x_set) != 1 and len(y_set) != 1:
                raise forms.ValidationError('Please draw your ships either horizontally or vertically!')

            if x != list(range(x[0], len(x) + x[0])) and y != list(range(y[0], len(y) + y[0])):
                raise forms.ValidationError('You cannot divide one big ship into several smaller ones!')

        return ships

main/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_list_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, FormView, TemplateView

from main.ai import ai_init, ai_moves
from main.forms import NewGameForm
from main.models import BOARD_SIZE, Game, SHIPS, State


class HomepageView(TemplateView):
    template_name = 'main/homepage.html'


class NewGameView(FormView):
    template_name = 'main/new_game.html'
    form_class = NewGameForm

    def get_context_data(self, **kwargs):
        context = super(NewGameView, self).get_context_data(**kwargs)
        context['board_size'] = BOARD_SIZE
        context['ship_list'] = SHIPS
        return context

    def form_valid(self, form):
        player_board = json.dumps(form.cleaned_data['fields'])
        player_ships = json.dumps(form.cleaned_data['ships'])
        ai_board, ai_ships = ai_init()

        game = Game.objects.create(
            player=self.request.user,
            player_board=player_board,
            ai_board=ai_board,
            player_ships=player_ships,
            ai_ships=ai_ships,
        )

        return HttpResponseRedirect(game.get_absolute_url())

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(NewGameView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        games = Game.objects.filter(player=request.user)
        if games.count() > 0:
            return redirect(games[0].get_absolute_url())
        return super(NewGameView, self).get(request, *args, **kwargs)


class GameDetailView(DetailView):
    model = Game

    def get_context_data(self, **kwargs):
        context = super(GameDetailView, self).get_context_data(**kwargs)
        context['board_size'] = BOARD_SIZE
        context['player_board'] = self.object.player_board
        context['ai_board'] = self.object.ai_board.replace(str(State.FILLED), str(State.EMPTY))
        return context

    def get_object(self, queryset=None):
        obj = super(GameDetailView, self).get_object(queryset)
        if obj.player != self.request.user:
            raise PermissionDenied
        return obj


def move(request):
    x, y = request.POST.get('x', '0'), request.POST.get('y', '0')

    try:
        x, y = int(x), int(y)
    except (ValueError, IndexError):
        return HttpResponse('Illegal move!')

    game = get_list_or_404(Game, player=request.user.pk)[0]
    state = int(json.loads(game.ai_board)[x][y])
    countermoves, ai_sunk, player_sunk = [], [], []

    if state == State.EMPTY:
        state = State.MISSED
        countermoves, player_sunk = ai_moves(game)
    elif state == State.FILLED:
        state, ai_sunk = game.hit_ai_ship(x, y)

    game.update_ai_board(x, y, state)

    game_over = game.game_over()
    if game_over:
        game.delete()

    response = {
        'state': state,
        'countermoves': countermoves,
        'ai_sunk': ai_sunk,
        'player_sunk': player_sunk,
        'game_over': game_over,
    }

    return HttpResponse(json.dumps(response))

main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load staticfiles %}

    <title>Baseships Game</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'main/css.css' %}">

    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Baseships Game</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li>
                    <li><a href="{% url 'new_game' %}">New game</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="starter-template">
            {% block content %}{% endblock content %}
        </div>
    </div>

    <script src="//code.jquery.com/jquery-2.2.0.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block body_extra %}{% endblock body_extra %}

</body>
</html>

main/templates/main/game_detail.html
{% extends "base.html" %}

{% block content %}
    <h1 id="id_game_over"></h1>

    <h2>Opponent</h2>
    {% with board_owner='ai' %}
        {% include 'main/snippets/board.html' %}
    {% endwith %}

    <h2>You</h2>
    {% with board_owner='player' %}
        {% include 'main/snippets/board.html' %}
    {% endwith %}

    <h3>Log</h3>
    <div id="log"></div>
{% endblock content %}

{% block body_extra %}
    <script>
        $(function(){
            var color;
            var player_board = {{ player_board|safe }};
            var ai_board = {{ ai_board|safe }};
            var $log = $('#log');
            var buttons_active = true;

            var colors = {
                0: 'silver',
                1: 'green',
                2: 'white',
                3: 'red',
                4: 'blue'
            };

            var messages = {
                2: 'missed',
                3: 'hit a ship',
                4: 'sunk a ship'
            };

            // populate users' boards

            function populate(board, owner) {
                for(var i = 0; i < board.length; ++i) {
                    for (var j = 0; j < board.length; ++j) {
                        color = colors[parseInt(board[i][j])];
                        $('#id_' + owner + 'field_' + i + '_' + j).css('background-color', color);
                    }
                }
            }

            populate(player_board, 'player');
            populate(ai_board, 'ai');

            // set up the log

            function log_ai(state) { log(state, 'Opponent'); }

            function log_player(state) { log(state, 'You'); }

            function log(state, user) {
                $log.append('<p>' + user + ' ' + messages[state] + '!</p>');
            }

            // perform requested move

            function ai_move(cm) {
                var state = parseInt(cm.state);
                color = colors[state];
                $('#id_playerfield_' + cm.x + '_' + cm.y).css('background-color', color);
                log_ai(state);
            }

            function move(data, button) {
                var i;
                button.css('background-color', colors[data.state]);
                log_player(data.state);

                for (i = 0; i < data.ai_sunk.length; ++i) {
                    $('#id_aifield_' + data.ai_sunk[i][0] + '_' + data.ai_sunk[i][1]).css('background-color', colors[4]);
                }

                setTimeout(function () {
                    for (var i = 0; i < data.countermoves.length; ++i) {
                        var cm = data.countermoves[i];
                        ai_move(cm);
                    }

                    for (i = 0; i < data.player_sunk.length; ++i) {
                        $('#id_playerfield_' + data.player_sunk[i][0] + '_' + data.player_sunk[i][1]).css('background-color', colors[4]);
                    }

                    if (data.game_over == 'V') {
                        $('#id_game_over').show().html('You win!');
                    }
                    else if (data.game_over == 'D') {
                        $('#id_game_over').show().html('You lose!');
                    }
                    else {
                        buttons_active = true;
                    }
                }, 500);
            }

            $('#board_ai').find('button').click(function() {
                var $this = $(this);

                if(buttons_active && $this.css('background-color') == 'rgb(192, 192, 192)') {
                    buttons_active = false;

                    var indexes = JSON.parse($this.val());

                    $.ajax({
                        dataType: "json",
                        method: "post",
                        url: '/move',
                        data: {
                            'x': indexes[0],
                            'y': indexes[1],
                            'csrfmiddlewaretoken': '{{ csrf_token }}'
                        },
                        success: function (data) {
                            move(data, $this);
                        }
                    });
                }
            });
        });
    </script>
{% endblock body_extra %}

main/templates/main/homepage.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome to Baseships Game!</h1>
{% endblock content %}

main/templates/main/new_game.html
{% extends "base.html" %}

{% block content %}
    {% if form.errors %}
        {% for _, errors in form.errors.items %}
            {{ errors }}
        {% endfor %}
    {% endif %}

    <form action="" method="post" id="id_board">
        <label>
            Select ship to build:
            <select id="id_ships_list">
                {% for ship in ship_list %}
                    <option value="{{ forloop.counter0 }}">{{ ship }}-element ship</option>
                {% endfor %}
            </select>
        </label>

        {% csrf_token %}
        {{ form.fields }}
        {{ form.ships }}

        {% include 'main/snippets/board.html' %}
        <input type="submit" value="START">
    </form>
{% endblock content %}

{% block body_extra %}
    <script>
        $(function(){
            var tmp, indexes, position;
            var $fields = $('#id_fields');
            var $ships_list = $('#id_ships_list');
            var ships = [];

            $fields.val(
                new Array({{ board_size }} * {{ board_size }} + 1).join('0')
            );

            $('button').click(function() {
                if($(this).css('background-color') == 'rgb(192, 192, 192)') {
                    indexes = JSON.parse($(this).val());
                    $(this).css('background-color', 'green');

                    position = {{ board_size }} * parseInt(indexes[0]) + parseInt(indexes[1]);
                    tmp = $fields.val().substr(0, position) + '1' + $fields.val().substr(position + 1);

                    $fields.val(tmp);
                    ships[$ships_list.val()].push(indexes);
                }
            });

            // collecting ships

            {% for ship in ship_list %}ships.push([]);{% endfor %}

            $('select').change(function() {
                for(var i = 0; i < ships.length; ++i) {
                    var color = 'black';

                    if(i == $(this).val()) {
                        color = 'green';
                    }

                    for(var j = 0; j < ships[i].length; ++j) {
                        $('#id_field_' + ships[i][j][0] + '_' + ships[i][j][1]).css('background-color', color)
                    }
                }
            });

            $('form').submit(function() {
                $('#id_ships').val(JSON.stringify(ships));
            });
        });
    </script>
{% endblock body_extra %}

main/templates/main/snippets/board.html
<div class="board" id="board_{{ board_owner }}">
    {% for i in "x"|rjust:board_size %}
        <div class="board_row">
            {% for j in "x"|rjust:board_size %}
                <button type="button"
                        id="id_{{ board_owner }}field_{{ forloop.parentloop.counter0 }}_{{ forloop.counter0 }}"
                        value="[{{ forloop.parentloop.counter0 }}, {{ forloop.counter0 }}]">
                </button>
            {% endfor %}
        </div>
    {% endfor %}
</div>